create table daily_briefings (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  briefing_date date,
  city text,
  temperature numeric,
  weather text,
  country text,
  country_capital text,
  country_population bigint,
  ai_briefing text
);
